services:
  backend:
    image: marselchi/dndbackend:latest
    container_name: server
    env_file: .env
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '0.5'
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:18-alpine
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 350M
          cpus: '0.5'

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app-net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge