import { Character } from "@/types/character";


export const mockCharacters: Character[] = [
  {
    id: "1",
    name: "Elena Blackwood",
    profession: "Arcane Scholar",
    appearDate: "Chapter 1",
    status: "Active",
    affiliation: "The Silver Order",
    description:
      "A brilliant mage who discovered the ancient texts of the forgotten realm. Her research into dimensional magic has made her both celebrated and feared among her peers.",
    race: "Human",
    age: 34,
    importantNotes: "Holds the key to the dimensional gate",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "2",
    name: "Kael Stormwind",
    profession: "Knight Commander",
    appearDate: "Chapter 2",
    status: "Active",
    affiliation: "Royal Guard",
    description:
      "A seasoned warrior who has served the kingdom for over two decades. Known for his unwavering loyalty and tactical brilliance on the battlefield.",
    race: "Human",
    age: 45,
    importantNotes: "Former mentor of the protagonist",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "3",
    name: "Zyx the Wanderer",
    profession: null,
    appearDate: "Chapter 5",
    status: "Unknown",
    affiliation: null,
    description:
      "A mysterious figure who appears at crucial moments throughout the story. Their true intentions remain unclear.",
    race: "Unknown",
    age: null,
    importantNotes: null,
    pictureUrl: null,
  },
  {
    id: "4",
    name: "Aria Moonwhisper",
    profession: "Healer",
    appearDate: "Chapter 3",
    status: "Active",
    affiliation: "Temple of Dawn",
    description:
      "A gifted healer with the rare ability to commune with spirits. She carries the burden of seeing the fate of those she heals.",
    race: "Elf",
    age: 127,
    importantNotes: "Can foresee death",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "5",
    name: "Grimjaw",
    profession: "Mercenary",
    appearDate: "Chapter 4",
    status: "Deceased",
    affiliation: "The Black Company",
    description:
      "A brutal warrior who lived by the sword. His death marked a turning point in the war against the shadow forces.",
    race: "Orc",
    age: 38,
    importantNotes: "Sacrificed himself to save the village",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "6",
    name: "Theo Brightheart",
    profession: "Bard",
    appearDate: "Chapter 1",
    status: "Active",
    affiliation: "Wandering Minstrels Guild",
    description:
      "A cheerful bard whose songs carry magical properties. He travels the land collecting stories and spreading hope through music.",
    race: "Halfling",
    age: 28,
    importantNotes: "His lute is a legendary artifact",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "7",
    name: "Morgana Shadowveil",
    profession: "Assassin",
    appearDate: "Chapter 6",
    status: "Active",
    affiliation: "The Silent Blade",
    description:
      "Once a noble's daughter, now the most feared assassin in the realm. She seeks revenge against those who destroyed her family.",
    race: "Human",
    age: 29,
    importantNotes: "Has a personal vendetta against the king",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "8",
    name: "Ironbeard",
    profession: "Blacksmith",
    appearDate: "Chapter 2",
    status: "Active",
    affiliation: "Dwarven Mining Consortium",
    description:
      "The finest weaponsmith in the mountain kingdoms. His creations are said to be imbued with the spirit of the mountains themselves.",
    race: "Dwarf",
    age: 156,
    importantNotes: "Created the legendary sword Dawnbreaker",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "9",
    name: "Whisper",
    profession: "Spy",
    appearDate: "Chapter 7",
    status: "Active",
    affiliation: null,
    description:
      "A master of disguise who sells information to the highest bidder. No one knows their true face or name.",
    race: null,
    age: null,
    importantNotes: "May be multiple people",
    pictureUrl: null,
  },
  {
    id: "10",
    name: "Lord Vexarius",
    profession: "Necromancer",
    appearDate: "Prologue",
    status: "Active",
    affiliation: "The Dark Covenant",
    description:
      "The main antagonist who seeks to resurrect an ancient evil. His mastery over death magic has made him nearly immortal.",
    race: "Human (Undead)",
    age: 847,
    importantNotes: "His phylactery is hidden",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "11",
    name: "Luna Starfire",
    profession: "Astronomer",
    appearDate: "Chapter 8",
    status: "Active",
    affiliation: "Academy of Stars",
    description:
      "A brilliant astronomer who discovered the prophecy written in the stars. Her knowledge of celestial events proves crucial to the heroes.",
    race: "Human",
    age: 42,
    importantNotes: "Can predict celestial events",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "12",
    name: "Fenris",
    profession: "Beast Tamer",
    appearDate: "Chapter 4",
    status: "Active",
    affiliation: "Wild Frontier Rangers",
    description:
      "Raised by wolves in the northern wilderness, Fenris has an uncanny ability to communicate with and control wild beasts.",
    race: "Human",
    age: 25,
    importantNotes: "Bonded with an ancient wolf spirit",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "13",
    name: "Duchess Seraphina",
    profession: "Noble",
    appearDate: "Chapter 3",
    status: "Active",
    affiliation: "Royal Court",
    description:
      "A cunning politician who plays all sides. Her vast network of informants makes her one of the most powerful people in the kingdom.",
    race: "Human",
    age: 51,
    importantNotes: "Secret supporter of the rebellion",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "14",
    name: "Spark",
    profession: "Inventor",
    appearDate: "Chapter 9",
    status: "Active",
    affiliation: "Tinkers' Union",
    description:
      "A genius inventor whose contraptions range from brilliant to dangerous. Her mechanical companions are both helpful and chaotic.",
    race: "Gnome",
    age: 67,
    importantNotes: "Created a prototype airship",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "15",
    name: "Silent Thunder",
    profession: "Monk",
    appearDate: "Chapter 5",
    status: "Active",
    affiliation: "Monastery of the Eternal Storm",
    description:
      "A warrior monk who has taken a vow of silence. He communicates through gestures and his devastating martial arts speak for him.",
    race: "Human",
    age: 35,
    importantNotes: "Can channel lightning through meditation",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "16",
    name: "Captain Redmane",
    profession: "Pirate",
    appearDate: "Chapter 10",
    status: "Active",
    affiliation: "The Crimson Fleet",
    description:
      "The most notorious pirate on the seven seas. Despite her reputation, she follows a strict code of honor among thieves.",
    race: "Human",
    age: 39,
    importantNotes: "Owns a map to the lost treasure",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "17",
    name: "The Oracle",
    profession: "Seer",
    appearDate: "Chapter 1",
    status: "Unknown",
    affiliation: null,
    description:
      "An ancient being who speaks in riddles and prophecies. Many seek their wisdom, but few understand their cryptic messages.",
    race: "Unknown",
    age: null,
    importantNotes: "Has never been wrong",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "18",
    name: "Bramble",
    profession: "Druid",
    appearDate: "Chapter 6",
    status: "Active",
    affiliation: "Circle of the Wild",
    description:
      "A druid who has spent centuries protecting the ancient forest. She can transform into any creature that dwells within her domain.",
    race: "Elf",
    age: 312,
    importantNotes: "The forest responds to her emotions",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "19",
    name: "Marcus Stone",
    profession: "Soldier",
    appearDate: "Chapter 2",
    status: "Retired",
    affiliation: "Former Royal Army",
    description: null,
    race: "Human",
    age: 62,
    importantNotes: null,
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "20",
    name: "Nightshade",
    profession: "Alchemist",
    appearDate: "Chapter 7",
    status: "Active",
    affiliation: "Underground Market",
    description:
      "A mysterious alchemist who deals in rare and often dangerous substances. Their potions can cure or kill with equal efficiency.",
    race: "Tiefling",
    age: 44,
    importantNotes: "Knows the antidote to any poison",
    pictureUrl: "/placeholder.svg?height=200&width=200",
  },
]
